-- Product Analytics Tables
-- Types verified against existing schema:
--   products.id        → bigint  (BIGINT GENERATED BY DEFAULT AS IDENTITY)
--   auth.users.id      → uuid
--   profiles.id        → uuid    (references auth.users)
--   cart_items.id      → bigint  (same pattern used here)
--   cart_items.user_id → uuid
-- ─────────────────────────────────────────────────────────────────────────────

begin;

-- ── product_views: deduped view events ───────────────────────────────────────
-- Used for: counting unique product views with 30-min dedup window
create table if not exists public.product_views (
  id         bigint      primary key generated always as identity,
  product_id bigint      not null references public.products(id) on delete cascade,
  user_id    uuid        null     references auth.users(id)       on delete set null,
  session_id text        not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_product_views_product_id ON public.product_views(product_id);
create index if not exists idx_product_views_user_id    ON public.product_views(user_id);
create index if not exists idx_product_views_session    ON public.product_views(session_id);
create index if not exists idx_product_views_created_at ON public.product_views(created_at);

-- ── product_events: full funnel tracking ─────────────────────────────────────
-- Tracks: view | add_to_cart | checkout_start | purchase
create table if not exists public.product_events (
  id         bigint      primary key generated always as identity,
  product_id bigint      not null references public.products(id) on delete cascade,
  user_id    uuid        null     references auth.users(id)       on delete set null,
  session_id text        not null,
  event_type text        not null check (event_type in ('view', 'add_to_cart', 'checkout_start', 'purchase')),
  created_at timestamptz not null default now()
);

create index if not exists idx_product_events_product_id  ON public.product_events(product_id);
create index if not exists idx_product_events_event_type  ON public.product_events(event_type);
create index if not exists idx_product_events_created_at  ON public.product_events(created_at);
create index if not exists idx_product_events_user_id     ON public.product_events(user_id);

commit;
