-- Create product_features table to store product feature metadata in a normalized structure.
-- This table is linked to products and supports ordering of features.

CREATE TABLE IF NOT EXISTS product_features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
);

-- Backfill existing product feature data from the legacy products.features field when possible.
-- This handles JSON arrays and comma-separated values.

INSERT INTO product_features (product_id, name, sort_order)
SELECT
  p.id,
  trim(value) AS name,
  row_number() OVER (PARTITION BY p.id ORDER BY (SELECT 1)) - 1 AS sort_order
FROM products p,
LATERAL (
  SELECT * FROM (
    SELECT jsonb_array_elements_text(p.features::jsonb) AS value
    WHERE p.features IS NOT NULL
      AND p.features <> ''
      AND p.features LIKE '[%'
    UNION ALL
    SELECT unnest(string_to_array(regexp_replace(p.features, '[\[\]"]', '', 'g'), ',')) AS value
    WHERE p.features IS NOT NULL
      AND p.features <> ''
      AND p.features NOT LIKE '[%'
  ) data
) feature_values
WHERE trim(feature_values.value) <> '';
